name: imossadmin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  sizer:
  get:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 

flutter:

  uses-material-design: true

  assets:
    - resources/images/
    - resources/logo/